# Assignment 1: NumPy Basics

This notebook contains basic NumPy operations such as array creation,
statistical calculations, arithmetic operations, and matrix creation.

In [2]:
import numpy as np

In [ ]:
# Creating a NumPy array containing integer values
numbers = np.array([10, 20, 30, 40, 50])

print("NumPy Array:")
print(numbers)

NumPy Array:
[10 20 30 40 50]


In [ ]:
# Using built-in NumPy functions to calculate basic operations on the array
print("Mean:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))
print("Sum:", np.sum(numbers))

Mean: 30.0
Maximum: 50
Minimum: 10
Sum: 150


In [7]:
# Creating two arrays
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print("Array 1:", arr_1)
print("Array 2:", arr_2)

Array 1: [1 2 3]
Array 2: [4 5 6]


In [8]:
# Performing addition and multiplication of the two arrays
print("Addition:", arr_1 + arr_2)
print("Multiplication:", arr_1 * arr_2)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [9]:
# Creating a 3 × 3 matrix using NumPy
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("3 x 3 Matrix:")
print(matrix)

3 x 3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
